# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0010_puzzle_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_list',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
