# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0011_goal_list_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
    ]
