# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0015_dedicated_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_list',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
