# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0016_event_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_projects',
            name='resources',
            field=models.CharField(default='Url', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
