# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0017_auto_20170112_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea_Brainstorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=350)),
            ],
        ),
    ]
