# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0019_book_select'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Select',
        ),
    ]
