# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0020_delete_book_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle_list',
            name='answer',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
