# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0021_puzzle_list_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle_list',
            name='input_answer',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
