# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0022_puzzle_list_input_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1100)),
            ],
        ),
    ]
