# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0023_testview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_list',
            name='content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='testview',
            name='content',
            field=models.TextField(),
        ),
    ]
