# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0026_person_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
