# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0027_book_list_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_list',
            name='commitment',
            field=models.TextField(default='ENTER SYLLABUS SUMMARY HERE'),
        ),
        migrations.AddField(
            model_name='course_list',
            name='timeframe',
            field=models.CharField(default='timeframe', max_length=150),
        ),
        migrations.AddField(
            model_name='course_list',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
