# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0028_auto_20170127_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='category',
            field=models.CharField(default='Research, Interest, Python', max_length=150),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event_list',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
