# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0029_auto_20170201_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.CharField(default='Research, Interest, Script, School', max_length=150),
        ),
    ]
