# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0030_auto_20170203_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_projects',
            name='category',
            field=models.CharField(choices=[('Script', 'Script'), ('SP_current', 'SideProject_Current'), ('SP_future', 'SideProject_Future'), ('Script_I', 'Script_Idea'), ('SP_I', 'SideProject_Idea')], default='Script', max_length=60),
        ),
    ]
