# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0031_side_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side_projects',
            name='category',
            field=models.CharField(choices=[('Script_C', 'Script_Current'), ('Script_F', 'Script_Future'), ('SP_current', 'SideProject_Current'), ('SP_future', 'SideProject_Future'), ('Script_I', 'Script_Idea'), ('SP_I', 'SideProject_Idea')], default='Script', max_length=60),
        ),
    ]
