# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0033_auto_20170228_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='slug_field',
        ),
    ]
