# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0034_remove_blog_post_slug_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ran_event_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
            ],
        ),
    ]
