# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0036_remove_ran_event_list_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ran_event_list',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
