# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0037_ran_event_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ran_event_list',
            name='start_time',
            field=models.TimeField(default=datetime.time(22, 4, 22, 458938)),
        ),
    ]
