# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0038_auto_20170318_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_projects',
            name='weight',
            field=models.CharField(choices=[(2, 2), (1, 1)], default=1, max_length=60),
        ),
        migrations.AlterField(
            model_name='ran_event_list',
            name='start_time',
            field=models.TimeField(default=datetime.time(11, 49, 6, 705504)),
        ),
    ]
