# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0040_auto_20170427_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side_projects',
            name='category',
        ),
        migrations.RemoveField(
            model_name='side_projects',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='side_projects',
            name='timeframe',
        ),
        migrations.RemoveField(
            model_name='side_projects',
            name='weight',
        ),
        migrations.AddField(
            model_name='side_projects',
            name='days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='ran_event_list',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 35, 50, 417877)),
        ),
    ]
