# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 22:39
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeline', '0043_auto_20170516_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='screen_shot',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='ran_event_list',
            name='start_time',
            field=models.TimeField(default=datetime.time(18, 39, 53, 642757)),
        ),
    ]
